package ee.tuleva.onboarding.banking.check.payment;

public enum PaymentCheckType {
  PAYMENT_BLOCKED,
  PAYOUT_BLOCKED,
  PAYOUT_OVERDUE,
  PAYMENT_MISROUTED,
  PAYMENT_REJECTED,
  PAYOUT_WITHOUT_REQUEST,
  DUPLICATE_PAYOUT,
  UNMODELLED_DEBIT,
  STATEMENT_UNPROCESSABLE,
  UNCLASSIFIED_BANK_OPERATION,
  PAYMENT_STUCK,
  WRONG_NAV_ISSUANCE,
  PAYMENT_NOT_EXECUTED,
  PHANTOM_DEBIT,
  DEBIT_MISMATCH,
  PAYMENT_INDETERMINATE
}
