version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: io.sentry:sentry-spring-boot-starter
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: com.sun.xml.ws:jaxws-rt
    versions:
    - 3.0.0
  - dependency-name: org.eclipse.persistence:org.eclipse.persistence.moxy
    versions:
    - 3.0.0
  - dependency-name: org.codehaus.groovy:groovy
    versions:
    - 3.0.7
  - dependency-name: org.springframework.cloud:spring-cloud-sleuth
    versions:
    - 3.0.1
  - dependency-name: io.sentry:sentry-logback
    versions:
    - 4.2.0
  - dependency-name: org.bouncycastle:bcpkix-jdk15on
    versions:
    - "1.68"
  - dependency-name: de.codecentric:spring-boot-admin-dependencies
    versions:
    - 2.4.0
  - dependency-name: commons-net:commons-net
    versions:
    - 3.8.0
  - dependency-name: com.vladmihalcea:hibernate-types-52
    versions:
    - 2.10.3
  - dependency-name: org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure
    versions:
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
  - dependency-name: org.glassfish.jersey.inject:jersey-hk2
    versions:
    - 3.0.1
