coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%
      aml:
        paths:
          - "src/main/java/ee/tuleva/onboarding/aml/**"
        target: 97%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
