package ee.tuleva.onboarding.account

import com.google.common.collect.Lists

import static ee.tuleva.onboarding.fund.FundFixture.*

class AccountStatementFixture {

  public static List<FundBalance> activeTuleva2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarStockFund())
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarBondFund())
          .build()
  )

  public static List<FundBalance> activeExternal2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv2ndPillarFund())
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarBondFund())
          .build()
  )

  public static List<FundBalance> inactiveTuleva2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(0.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(0.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv2ndPillarFund())
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarBondFund())
          .build()
  )

  public static List<FundBalance> inactiveExternal2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarBondFund())
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv2ndPillarFund())
          .build()
  )

  public static List<FundBalance> fullyExternal2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv2ndPillarFund())
          .build()
  )

  public static List<FundBalance> onlyActiveTuleva2ndPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(0.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(0.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva2ndPillarStockFund())
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv2ndPillarFund())
          .build()
  )

  public static List<FundBalance> activeTuleva3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build(),
      FundBalance.builder()
          .value(200.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(190.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(exitRestricted3rdPillarFund())
          .units(345.67)
          .build()
  )

  public static List<FundBalance> activeExternal3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv3rdPillarFund())
          .units(456.78)
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build()
  )

  public static List<FundBalance> activeTuleva3rdPillarFund = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build()
  )

  public static List<FundBalance> inactiveTuleva3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(0.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(0.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv3rdPillarFund())
          .units(456.78)
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build()
  )

  public static List<FundBalance> inactiveExternal3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv3rdPillarFund())
          .units(456.78)
          .build()
  )

  public static List<FundBalance> fullyExternal3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv3rdPillarFund())
          .units(456.78)
          .build()
  )

  public static List<FundBalance> onlyActiveTuleva3rdPillarFundBalance = Lists.asList(
      FundBalance.builder()
          .value(0.0)
          .unavailableValue(0.0)
          .activeContributions(true)
          .contributions(0.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(tuleva3rdPillarFund())
          .units(234.56)
          .build(),
      FundBalance.builder()
          .value(100.0)
          .unavailableValue(0.0)
          .activeContributions(false)
          .contributions(90.0)
          .subtractions(0.0)
          .currency("EUR")
          .fund(lhv3rdPillarFund())
          .units(456.78)
          .build()
  )

}
