package ee.tuleva.onboarding.investment.check.fee;

enum FeeCheckType {
  LEDGER_ACCRUAL_CONSISTENCY,
  FEE_BASE_COMPLETENESS,
  CUSTODIAN_POSITION_COMPLETENESS,
  BLACKROCK_ADJUSTMENT_FRESHNESS,
  SETTLEMENT_COMPLETENESS,
  ACCRUAL_ROUNDING_DRIFT,
  CASH_SETTLEMENT_OBSERVED
}
