CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.third_pillar_transactions (
                                                                 id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                 reporting_date    DATE            NOT NULL,
                                                                 full_name         VARCHAR(255)    NOT NULL,
                                                                 personal_id       VARCHAR(255)    NOT NULL,
                                                                 account_no        VARCHAR(255)    NOT NULL,
                                                                 country           VARCHAR(255),
                                                                 transaction_type  VARCHAR(255)    NOT NULL,
                                                                 transaction_source VARCHAR(255),
                                                                 application_type  VARCHAR(255),
                                                                 share_amount      NUMERIC         NOT NULL,
                                                                 share_price       NUMERIC         NOT NULL,
                                                                 nav               NUMERIC         NOT NULL,
                                                                 transaction_value NUMERIC         NOT NULL,
                                                                 service_fee       NUMERIC,
                                                                 date_created      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                 fund_manager      VARCHAR(255),
                                                                 fund              VARCHAR(255),
                                                                 purpose_code      INTEGER,
                                                                 counterparty_name VARCHAR(255),
                                                                 counterparty_code VARCHAR(255),
                                                                 counterparty_bank_account VARCHAR(255),
                                                                 counterparty_bank VARCHAR(255),
                                                                 counterparty_bic  VARCHAR(255)
);
