package ee.tuleva.onboarding.audit;

public enum AuditEventType {
  LOGIN,
  GET_ACCOUNT_STATEMENT,
  GET_CASH_FLOWS,
  MANDATE_DENIED,
  SECOND_PILLAR_CONFIRM_PAGE_REACHED,
  THIRD_PILLAR_CONFIRM_PAGE_REACHED,
}
