package ee.tuleva.onboarding.investment.config;

public enum InvestmentParameter {
  TRACKING_BREACH_THRESHOLD,
  TRACKING_MAX_DAILY_RETURN,
  NAV_IMPACT_VOLUME_THRESHOLD,
  ESCALATION_LOOKBACK_DAYS,
  ESCALATION_THRESHOLD_DAYS,
  ESCALATION_NET_TD_THRESHOLD
}
