version: '3.8'
services:
  onboarding-service:
    image: "641866833894.dkr.ecr.eu-central-1.amazonaws.com/onboarding-service:${hash}"
    ports:
      - 5000:5000
    volumes:
      - /home/webapp/keystore.p12:/keystore.p12
      - /home/webapp/truststore.jks:/truststore.jks
    env_file:
      - .env

  nginx:
    image: public.ecr.aws/nginx/nginx:latest
    volumes:
      - /tmp/fullchain.pem:/tmp/fullchain.pem
      - /tmp/privkey.pem:/tmp/privkey.pem
      - /tmp/id.crt:/tmp/id.crt
      - /tmp/dhparam.pem:/tmp/dhparam.pem
      - .platform/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .platform/nginx/conf.d/01_ssl_proxy.conf:/etc/nginx/conf.d/01_ssl_proxy.conf
      - .platform/nginx/conf.d/elasticbeanstalk/00_application.conf:/etc/nginx/conf.d/elasticbeanstalk/00_application.conf
      - .platform/nginx/conf.d/elasticbeanstalk/01_redirect.conf:/etc/nginx/conf.d/elasticbeanstalk/01_redirect.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - onboarding-service
