version: '3.8'
services:
  onboarding-service:
    image: "641866833894.dkr.ecr.eu-central-1.amazonaws.com/onboarding-service:${hash}"
    ports:
      - 5000:5000
    volumes:
      - /home/webapp/truststore.jks:/truststore.jks
      - /home/webapp/jwt-keystore.p12:/jwt-keystore.p12
      - /home/webapp/partner-public-key1.pem:/partner-public-key1.pem # dev and pre-live, these are two identical files in production
      - /home/webapp/partner-public-key2.pem:/partner-public-key2.pem
    env_file:
      - .env

  nginx:
    image: public.ecr.aws/nginx/nginx:latest
    volumes:
      - /tmp/pension.tuleva.ee:/tmp/pension.tuleva.ee
      - /tmp/staging.tuleva.ee:/tmp/staging.tuleva.ee
      - .platform/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .platform/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .platform/nginx/conf.d/elasticbeanstalk/00_application.conf:/etc/nginx/conf.d/elasticbeanstalk/00_application.conf
      - .platform/nginx/conf.d/elasticbeanstalk/01_redirect.conf:/etc/nginx/conf.d/elasticbeanstalk/01_redirect.conf
      - .platform/nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
      - 443:443
    depends_on:
      - onboarding-service
    env_file:
      - .env
