version: '3.8'
services:
  onboarding-service:
    image: "641866833894.dkr.ecr.eu-central-1.amazonaws.com/onboarding-service:${hash}"
    ports:
      - 5000:5000
    volumes:
      - /home/webapp/keystore.p12:/keystore.p12
      - /home/webapp/truststore.jks:/truststore.jks
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/tmp/fullchain.pem
      - ./nginx/privkey.pem:/tmp/privkey.pem
      - ./nginx/id.crt:/tmp/id.crt
      - ./nginx/dhparam.pem:/tmp/dhparam.pem
      - ./etc/eb/.ebextensions/nginx/conf.d/01_ssl_proxy.conf:/etc/nginx/conf.d/01_ssl_proxy.conf
    ports:
      - 80:80
      - 443:443
