package ee.tuleva.onboarding.event;

public enum TrackableEventType {
  LOGIN,
  GET_ACCOUNT_STATEMENT,
  GET_CASH_FLOWS,
  MANDATE_SUCCESSFUL,
  MANDATE_DENIED,
  PAGE_VIEW,
  PAYMENT_LINK,
  CLICK,
  CAPITAL_TRANSFER_STATE_CHANGE
}
