package ee.tuleva.onboarding.ledger;

public enum SavingsFundTransactionType {
  PAYMENT_RECEIVED,
  PAYMENT_CANCEL_REQUESTED,
  PAYMENT_CANCELLED,
  UNATTRIBUTED_PAYMENT,
  PAYMENT_BOUNCE_BACK,
  PAYMENT_RESERVED,
  FUND_SUBSCRIPTION,
  FUND_TRANSFER,
  LATE_ATTRIBUTION,
  REDEMPTION_RESERVED,
  REDEMPTION_CANCELLED,
  REDEMPTION_REQUEST,
  FUND_CASH_TRANSFER,
  REDEMPTION_PAYOUT
}
