###REFRESH TOKEN
POST http://localhost:3000/oauth/refresh-token HTTP/1.1
Content-Type: application/json

//{ "refresh_token" : "eyJhbGciOiJSUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJVU0VSIiwiTUVNQkVSIl0sInRva2VuVHlwZSI6IlJFRlJFU0giLCJsYXN0TmFtZSI6IlZBTERNQSIsImZpcnN0TmFtZSI6IkpPUkRBTiIsImF0dHJpYnV0ZXMiOnsiZ3JhbnRUeXBlIjoiU01BUlRfSUQifSwic3ViIjoiMzg4MTIwMjI3NjIiLCJpYXQiOjE3MDg5NTE3OTgsImV4cCI6MTcwOTAzODE5OH0.JAeXVdEot-mYkbXhY6ekTr7BrDkr51KhJzJ4HurdNOED134LhoXWlUW4Y5-FatXEjH02QyE-1xAgIbOe-KSW_UU5XqSwJYkkjVeh9WqQ8HYzekB9prtxx8Zy6zK1SbSzSn1w0KvQuDn56_UItbbcLEefBLo2HW56EHE9HIBUIJ4PwLodS6dGsjThTordp49uJbB5anwhJ0rB3i0VrubNdc91UE4XpDaqmyvmQLNgG6gqxz1_rJLMEBge6fmaJqjzaKClPF6H6kcNn-Ox_bds-Yp74MY28wu0jYuS1TP4Rzhey1T1keTVcB2qtaElqMZ_DvID7pYvvbX2cfCtYdtQxQ" }

//Expired token
{ "refresh_token" : "eyJhbGciOiJSUzI1NiJ9.eyJsYXN0TmFtZSI6IlZBTERNQSIsImZpcnN0TmFtZSI6IkpPUkRBTiIsImF0dHJpYnV0ZXMiOnsiZ3JhbnRUeXBlIjoiU01BUlRfSUQifSwiYXV0aG9yaXRpZXMiOlsiVVNFUiIsIk1FTUJFUiJdLCJ0b2tlblR5cGUiOiJSRUZSRVNIIiwic3ViIjoiMzg4MTIwMjI3NjIiLCJpYXQiOjE3MDg5NTIyOTIsImV4cCI6MTcwODk1MjI5M30.QyG3jw8NYwpje9ktHTIxM2jdXINiykvXNxfKyJSbcRgS3T0Hkb1Iu4F5IqKRorHJJMpbzkorlHmFGzNivUIbi5aIXDT_4hIIMoCw78SJ56nHa6QdGH3OKXQ8OQbzMiTARA8wGE8MVUOWb7tRPXElYNyWidnYcm-rJ1G2lQ3CcAnIORFBdDAuzvId5DCo5IGf473OicjIOoiwhUyRqIpttLr5XE69nPIn5UT0R0LIn6NSNw8SJ4BukuKc_cipV5kxme7VQsB4SEA9SkW8L8yKZyBfVMY5rI6x1lpYDA40d2iRti3J-S-PHg8KwT32v2oVpMp7_OXr07ks5MP3z6Xj6Q" }
