GET https://api.sandbox-payments.montonio.com/pis/v2/merchants/aspsps
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3Nfa2V5IjoiMDcwZTljYWUtOWYwYy00MjNlLTkzNDUtNzBkNjI0YTA1NTc4IiwiZXhwIjoxNjYyOTc5NDcxfQ.0vk2Cs3KdNERjPyvtWNsVlEsMvPeuTKTJQhsmkylEP4
