package ee.tuleva.onboarding.kyb;

public enum KybCheckType {
  COMPANY_STRUCTURE,
  SOLE_MEMBER_OWNERSHIP,
  DUAL_MEMBER_OWNERSHIP,
  SOLE_BOARD_MEMBER_IS_OWNER,
  COMPANY_ACTIVE,
  RELATED_PERSONS_KYC,
  COMPANY_SANCTION,
  COMPANY_PEP,
  HIGH_RISK_NACE,
  COMPANY_LEGAL_FORM,
  SELF_CERTIFICATION,
  DATA_CHANGED
}
