UPDATE ledger.account SET name = name || ':TKF100'
WHERE name IN ('INCOMING_PAYMENTS_CLEARING', 'PAYOUTS_CASH_CLEARING',
               'FUND_INVESTMENT_CASH_CLEARING', 'FUND_UNITS_OUTSTANDING',
               'UNRECONCILED_BANK_RECEIPTS', 'BANK_FEE',
               'BANK_ADJUSTMENT', 'INTEREST_INCOME')
  AND purpose = 'SYSTEM_ACCOUNT';
