CREATE TABLE nav_report (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    nav_date date NOT NULL,
    fund_code text NOT NULL,
    account_type text NOT NULL,
    account_name text NOT NULL,
    account_id text,
    quantity numeric(20,8),
    market_price numeric(20,8),
    currency varchar(3) NOT NULL DEFAULT 'EUR',
    market_value numeric(20,8),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_nav_report PRIMARY KEY (id),
    CONSTRAINT uq_nav_report_date_fund_type_name
        UNIQUE (nav_date, fund_code, account_type, account_name)
);
CREATE INDEX idx_nav_report_fund_date ON nav_report (fund_code, nav_date);
