CREATE TABLE investment_td_attribution (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code text NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    period_type text NOT NULL,
    fund_return numeric(12, 8) NOT NULL,
    model_return numeric(12, 8) NOT NULL,
    td_geometric numeric(12, 8) NOT NULL,
    scaling_factor numeric(10, 8),
    mgmt_fee_drag numeric(12, 8),
    depot_fee_drag numeric(12, 8),
    cash_drag numeric(12, 8),
    non_security_drag numeric(12, 8),
    weight_deviation numeric(12, 8),
    transaction_costs numeric(12, 8),
    residual numeric(12, 8),
    business_days int,
    avg_aum numeric(19, 2),
    avg_cash_pct numeric(8, 6),
    checks jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_td_attribution UNIQUE (fund_code, period_start, period_end, period_type)
);

CREATE INDEX idx_td_attribution_fund ON investment_td_attribution(fund_code, period_start);

CREATE TABLE investment_td_attribution_detail (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribution_id bigint NOT NULL,
    isin text NOT NULL,
    instrument_name text,
    model_weight numeric(8, 6),
    avg_actual_weight numeric(8, 6),
    weight_dev_contribution numeric(12, 8),
    security_return numeric(12, 8),
    CONSTRAINT fk_td_attribution_detail FOREIGN KEY (attribution_id)
        REFERENCES investment_td_attribution(id) ON DELETE CASCADE,
    CONSTRAINT uq_td_attribution_detail UNIQUE (attribution_id, isin)
);

CREATE INDEX idx_td_attr_detail_attribution ON investment_td_attribution_detail(attribution_id);
