CREATE TABLE investment_instrument_fee (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin            varchar(12)     NOT NULL,
    instrument_name text            NOT NULL,
    published_ocf   numeric(10, 8)  NOT NULL,
    rebate_rate     numeric(10, 8)  NOT NULL DEFAULT 0,
    net_ocf         numeric(10, 8)  NOT NULL,
    valid_from      date            NOT NULL,
    valid_to        date,
    source          text,
    created_at      timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT uq_instrument_fee_isin_valid_from UNIQUE (isin, valid_from)
);

CREATE INDEX idx_instrument_fee_isin ON investment_instrument_fee(isin);
CREATE INDEX idx_instrument_fee_valid_from ON investment_instrument_fee(valid_from);
