ALTER TABLE fee_rate RENAME TO investment_fee_rate;
ALTER TABLE fee_accrual RENAME TO investment_fee_accrual;
ALTER TABLE depot_fee_tier RENAME TO investment_depot_fee_tier;
ALTER TABLE custody_fee_instrument_type RENAME TO investment_custody_fee_instrument_type;

ALTER TABLE investment_fee_rate RENAME CONSTRAINT fee_rate_pkey TO investment_fee_rate_pkey;
ALTER TABLE investment_fee_rate RENAME CONSTRAINT fee_rate_fund_code_fee_type_valid_from_key TO investment_fee_rate_fund_code_fee_type_valid_from_key;
ALTER INDEX fee_rate_fund_code_fee_type_idx RENAME TO investment_fee_rate_fund_code_fee_type_idx;
ALTER INDEX fee_rate_valid_from_idx RENAME TO investment_fee_rate_valid_from_idx;

ALTER TABLE investment_fee_accrual RENAME CONSTRAINT fee_accrual_pkey TO investment_fee_accrual_pkey;
ALTER TABLE investment_fee_accrual RENAME CONSTRAINT fee_accrual_fund_code_fee_type_accrual_date_key TO investment_fee_accrual_fund_code_fee_type_accrual_date_key;
ALTER INDEX fee_accrual_fee_month_idx RENAME TO investment_fee_accrual_fee_month_idx;
ALTER INDEX fee_accrual_fund_code_fee_type_fee_month_idx RENAME TO investment_fee_accrual_fund_code_fee_type_fee_month_idx;

ALTER TABLE investment_depot_fee_tier RENAME CONSTRAINT depot_fee_tier_pkey TO investment_depot_fee_tier_pkey;
ALTER TABLE investment_depot_fee_tier RENAME CONSTRAINT depot_fee_tier_min_aum_valid_from_key TO investment_depot_fee_tier_min_aum_valid_from_key;

ALTER TABLE investment_custody_fee_instrument_type RENAME CONSTRAINT custody_fee_instrument_type_pkey TO investment_custody_fee_instrument_type_pkey;
ALTER TABLE investment_custody_fee_instrument_type RENAME CONSTRAINT custody_fee_instrument_type_isin_valid_from_key TO investment_custody_fee_instrument_type_isin_valid_from_key;
