CREATE TABLE investment_ocf_snapshot_new (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code               text            NOT NULL,
    snapshot_month          date            NOT NULL,
    version                 int             NOT NULL,

    management_fee_rate     numeric(10, 8)  NOT NULL,
    depot_fee_rate          numeric(10, 8)  NOT NULL,
    underlying_fund_cost    numeric(10, 8)  NOT NULL,
    transaction_cost_rate   numeric(10, 8)  NOT NULL,
    total_ocf               numeric(10, 8)  NOT NULL,

    nav_date                date,
    nav_calculation_id      uuid,
    assets_under_management numeric(19, 2),

    management_fee_rate_id  bigint,

    depot_charged_to_fund   boolean,
    depot_tier_nav_date     date,
    depot_tier_basis        numeric(19, 2),

    txn_window_start        date,
    txn_window_end          date,
    txn_commissions         numeric(19, 2),
    txn_average_aum         numeric(19, 2),
    txn_nav_dates           text,

    complete                boolean         NOT NULL,
    checks                  text            NOT NULL DEFAULT '{}',

    calculated_at           timestamptz     NOT NULL DEFAULT now(),
    published_at            timestamptz,
    published_in            text,
    created_at              timestamptz     NOT NULL DEFAULT now(),

    CONSTRAINT investment_ocf_snapshot_fund_month_version_key
        UNIQUE (fund_code, snapshot_month, version),
    CONSTRAINT investment_ocf_snapshot_version_positive
        CHECK (version >= 1),
    CONSTRAINT investment_ocf_snapshot_published_in_needs_published_at
        CHECK (published_in IS NULL OR published_at IS NOT NULL)
);

INSERT INTO investment_ocf_snapshot_new
    (fund_code, snapshot_month, version, management_fee_rate, depot_fee_rate,
     underlying_fund_cost, transaction_cost_rate, total_ocf, complete, created_at)
SELECT
    fund_code, snapshot_month, 1, management_fee_rate, depot_fee_rate,
    underlying_fund_cost, transaction_cost_rate, total_ocf, false, created_at
FROM investment_ocf_snapshot;

DROP TABLE investment_ocf_snapshot;

ALTER TABLE investment_ocf_snapshot_new RENAME TO investment_ocf_snapshot;

CREATE INDEX idx_ocf_snapshot_fund ON investment_ocf_snapshot (fund_code, snapshot_month);
CREATE INDEX idx_ocf_snapshot_published ON investment_ocf_snapshot (fund_code, snapshot_month, published_at);
