CREATE TABLE investment_instrument_fee_split
(
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin              varchar(12)    NOT NULL,
    instrument_name   text           NOT NULL,
    published_ocf     numeric(10, 8) NOT NULL,
    rebate_rate       numeric(10, 8) NOT NULL DEFAULT 0,
    invoiced_fee_rate numeric(10, 8) NOT NULL DEFAULT 0,
    net_ocf           numeric(10, 8) NOT NULL,
    valid_from        date           NOT NULL,
    valid_to          date,
    source            text,
    created_at        timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT uq_instrument_fee_isin_valid_from_split UNIQUE (isin, valid_from),
    CONSTRAINT chk_instrument_fee_rebate_is_a_discount CHECK (rebate_rate >= 0),
    CONSTRAINT chk_instrument_fee_invoiced_is_a_charge CHECK (invoiced_fee_rate >= 0)
);

INSERT INTO investment_instrument_fee_split
    (id, isin, instrument_name, published_ocf, rebate_rate, invoiced_fee_rate, net_ocf,
     valid_from, valid_to, source, created_at)
SELECT id,
       isin,
       instrument_name,
       published_ocf,
       GREATEST(-rebate_rate, 0),
       GREATEST(rebate_rate, 0),
       net_ocf,
       valid_from,
       valid_to,
       source,
       created_at
FROM investment_instrument_fee;

DROP TABLE investment_instrument_fee;

ALTER TABLE investment_instrument_fee_split RENAME TO investment_instrument_fee;

ALTER TABLE investment_instrument_fee
    RENAME CONSTRAINT uq_instrument_fee_isin_valid_from_split TO uq_instrument_fee_isin_valid_from;

CREATE INDEX idx_instrument_fee_isin ON investment_instrument_fee (isin);
CREATE INDEX idx_instrument_fee_valid_from ON investment_instrument_fee (valid_from);
