CREATE TABLE investment_risk_indicator_point (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_type text NOT NULL,
    fund_code text NOT NULL,
    as_of_date date NOT NULL,
    source_keys text NOT NULL,
    risk_class int,
    observation_count int NOT NULL,
    volatility numeric(18, 12) NOT NULL,
    metrics jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_risk_indicator_point UNIQUE (indicator_type, fund_code, as_of_date)
);

CREATE INDEX idx_risk_indicator_point_series
    ON investment_risk_indicator_point(fund_code, indicator_type, as_of_date);

CREATE TABLE investment_risk_indicator_publication (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_type text NOT NULL,
    fund_code text NOT NULL,
    evaluation_date date NOT NULL,
    published_class int,
    raw_latest_class int,
    previous_published_class int,
    published_since date,
    streak_reference_points int NOT NULL,
    window_reference_points int NOT NULL,
    matching_reference_points int NOT NULL,
    status text NOT NULL,
    notified boolean NOT NULL DEFAULT false,
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_risk_indicator_publication UNIQUE (indicator_type, fund_code, evaluation_date)
);

CREATE INDEX idx_risk_indicator_publication_fund
    ON investment_risk_indicator_publication(fund_code, indicator_type, evaluation_date);

CREATE TABLE investment_risk_indicator_disclosure (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_type text NOT NULL,
    fund_code text NOT NULL,
    disclosed_class int NOT NULL,
    disclosed_from date NOT NULL,
    document text NOT NULL,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_risk_indicator_disclosure UNIQUE (indicator_type, fund_code, disclosed_from)
);

-- One row per month in which the Slack digest was sent. The unique constraint is what makes the
-- "on or after the 4th business day, and not yet sent this month" trigger idempotent across
-- instances and self-healing after a failed morning.
CREATE TABLE investment_risk_indicator_digest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_month date NOT NULL,
    complete boolean NOT NULL DEFAULT true,
    sent_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_risk_indicator_digest UNIQUE (digest_month)
);

INSERT INTO investment_risk_indicator_disclosure
    (indicator_type, fund_code, disclosed_class, disclosed_from, document)
VALUES
    ('SRRI', 'TUK75', 5, DATE '2026-03-19', 'Pohiteave TUK75 19.03.2026'),
    ('SRRI', 'TUK00', 4, DATE '2026-03-19', 'Pohiteave TUK00 19.03.2026'),
    ('SRRI', 'TUV100', 5, DATE '2026-03-19', 'Pohiteave TUV100 19.03.2026'),
    ('SRI', 'TKF100', 4, DATE '2026-02-27', 'Pohiteave TKF100 27.02.2026');
