CREATE TABLE investment_fee_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code       text        NOT NULL,
    fee_type        text        NOT NULL,
    charged_to_fund boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_to        date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,

    CONSTRAINT investment_fee_policy_fund_code_fee_type_valid_from_key
        UNIQUE (fund_code, fee_type, valid_from)
);

CREATE INDEX investment_fee_policy_fund_code_fee_type_idx
    ON investment_fee_policy (fund_code, fee_type);

-- The depot fee is covered by the management fee: Tuleva charges the management fee and
-- pays the depoopank out of that income, so no fund bears a depot fee of its own. Such a
-- fee is still accrued into investment_fee_accrual to track the cost, but it stays out of
-- the fund's NAV and out of its ledger. Every fund gets an explicit row from its inception
-- date; close it and open a new one with charged_to_fund = true if that ever changes.
-- Absence of a row means the fund is charged the fee.
INSERT INTO investment_fee_policy (fund_code, fee_type, charged_to_fund, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'DEPOT', false, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'DEPOT', false, DATE '2026-02-02', 'MIGRATION');
