CREATE TABLE investment_fee_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code       text        NOT NULL,
    fee_type        text        NOT NULL,
    include_in_nav  boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_to        date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,

    CONSTRAINT investment_fee_policy_fund_code_fee_type_valid_from_key
        UNIQUE (fund_code, fee_type, valid_from)
);

CREATE INDEX investment_fee_policy_fund_code_fee_type_idx
    ON investment_fee_policy (fund_code, fee_type);

-- The depoopank deducts the depot fee directly from the pension funds, so it must not
-- reduce the NAV we calculate. The accrual is still recorded for accounting.
-- Absence of a row means the fee is included in NAV.
INSERT INTO investment_fee_policy (fund_code, fee_type, include_in_nav, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION');
