-- One amount per accrual, named for what it is. This is the expand half; the drop comes later.
--
-- The net/gross pair only ever meant something while a VAT rate was applied on top of the net
-- figure. That multiplication is gone: investment_depot_fee_tier.annual_rate already includes VAT,
-- so the depot accrual computed from it is the VAT-inclusive amount, and fund management is a
-- VAT-exempt service, so the management accrual has no VAT component to separate out. Both
-- calculators therefore wrote the same number into both columns.
--
-- Gross is the accurate name for what survives: the amount actually charged. Keeping "net" on a
-- VAT-inclusive figure is the kind of label that gets believed.
--
-- Nothing is lost by eventually dropping the net column. Management accruals have always had
-- daily_amount_net = daily_amount_gross, and every fund carries an explicit DEPOT rate row of 0,
-- so the only rows where the old VAT multiplication could have made them differ are zero on both
-- sides. Verify before deploying if you want the receipt:
--
--   SELECT count(*) FROM investment_fee_accrual WHERE daily_amount_net <> daily_amount_gross;
--
-- Why this only drops NOT NULL rather than the column. A Flyway migration is one-way; an ECS
-- rollback is not. Dropping the column here and then rolling the deploy back -- health checks
-- fail, ECS reverts the task definition -- puts the image back while the schema stays ahead, and
-- the previous image still names daily_amount_net in its INSERT. That fails inside
-- FeeCalculationService.recordDailyFees, which is a step in the NAV pipeline rather than a side
-- report, and it fails silently: ECS rolls back on its own while CI stays green, so the first
-- symptom is the daily fee accrual having stopped for every fund. The same window opens for a few
-- minutes during any rolling deploy, where an old task can run the fee job after the migration has
-- landed. Keeping the column nullable lets the old image keep writing both amounts.
--
-- Making the column nullable is only half of it, and the missing half is the dangerous one. If the
-- new image simply stopped writing daily_amount_net, every row it wrote would be NULL -- and the
-- old image does not merely write that column, it READS it: getUnsettledAccrual sums
-- daily_amount_net straight into the NAV's fee liability. SUM skips NULLs, so a rollback onto
-- those rows would understate the management fee liability and publish an OVERSTATED unit price.
-- That is a wrong published NAV, not a reporting nuisance.
--
-- So FeeAccrualRepository.save writes the same amount to both columns for as long as both exist.
-- Nothing reads daily_amount_net in the new image; it exists purely so a rollback lands on correct
-- data. Remove the dual-write in the same change that drops the column.
--
-- DROP COLUMN belongs in the next release, once nothing deployed references the column, together
-- with vat_rate, which is nullable and unread but still named by the old image's INSERT.
--
-- Metabase reads this table directly. Questions selecting daily_amount_net keep working while the
-- dual-write is in place, and break on the drop -- so move them to daily_amount_gross before that
-- release. The management fee drag in "TD Attribution + OCF Calculation" is one.

ALTER TABLE investment_fee_accrual ALTER COLUMN daily_amount_net DROP NOT NULL;
