-- How a fee rate row gets its rate:
--   FIXED -- annual_rate is the rate
--   TIER  -- the rate comes from investment_depot_fee_tier, by the funds' combined aktiva two
--            month ends back, valid at the fee month. Aktiva, not AUM: AUM is net of liabilities
--            and is the management fee's base. See DepotFeeCalculator.
--
-- Before this, "use the tier" was expressed by having no row at all, so a lapsed valid_to or a
-- deleted row silently switched a fund from a 0 rate to the tier rate. Using the tier is now a
-- row you add rather than a row you remove, and a missing row means no fee.
-- The three rules this column carries -- the value is FIXED or TIER, TIER is only meaningful for
-- DEPOT, and a TIER row leaves annual_rate at 0 -- are enforced in code and asserted over this
-- table in FeeRepositoriesIntegrationTest, not by CHECK constraints. A CHECK added here by ALTER
-- is not re-evaluated correctly by H2 once a second Spring context has opened the shared test
-- database: every insert that relies on the column default then fails with "Check constraint
-- invalid", which took the whole fee and NAV suite red while PostgreSQL was perfectly happy.
--
-- varchar, not text: H2 maps text to a CLOB, which cannot be compared inside a CHECK constraint.
--
-- Whichever way a rate is resolved, it must be entered VAT-inclusive. The accrual computed from it
-- is stored in investment_fee_accrual.daily_amount_gross and posted to the ledger as the amount
-- charged, with no VAT step anywhere after this point. The tier rates already satisfy this; a
-- hand-entered FIXED depot rate must too, or the column name stops being true.
--
-- This migration is structural only. Switching the depot fee from its 0 rate to the tier is a
-- dated business change and lives in its own migration, V1_246, so that the date can be moved
-- without touching this one.
ALTER TABLE investment_fee_rate
    ADD COLUMN rate_source varchar(10) DEFAULT 'FIXED' NOT NULL;
