CREATE TABLE investment_fee_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code       text        NOT NULL,
    fee_type        text        NOT NULL,
    charged_to_fund boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_to        date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,

    CONSTRAINT investment_fee_policy_fund_code_fee_type_valid_from_key
        UNIQUE (fund_code, fee_type, valid_from),
    CONSTRAINT investment_fee_policy_valid_range_check
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX investment_fee_policy_fund_code_fee_type_idx
    ON investment_fee_policy (fund_code, fee_type);

-- Whether a fee is charged to the fund (it reduces NAV and is posted to the fund's ledger) or is
-- borne by Tuleva and only accrued to track the cost.
--
-- The depot fee is covered by the management fee: Tuleva charges the management fee and pays the
-- depoopank out of that income, so no fund bears a depot fee of its own. Such a fee is still
-- accrued into investment_fee_accrual to track the cost, but it stays out of the fund's NAV and out
-- of its ledger. Close a row and open a new one with charged_to_fund = true if that ever changes.
--
-- Every fund and fee type has an explicit row from the fund's inception date. There is no default:
-- a missing or an overlapping row makes the lookup throw, because guessing "charged" would put a
-- fee back into a published unit price and guessing "not charged" would stop the management fee
-- from accruing -- both silently. Add rows here when adding a fund.
INSERT INTO investment_fee_policy (fund_code, fee_type, charged_to_fund, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'DEPOT', false, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'DEPOT', false, DATE '2026-02-02', 'MIGRATION'),
       ('TUK75', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'MANAGEMENT', true, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'MANAGEMENT', true, DATE '2026-02-02', 'MIGRATION');
