-- The depot fee: who bears it (investment_fee_policy), where its rate comes from
-- (investment_fee_rate.rate_source), and when the real rate starts (2026-09-18).

-- charged_to_fund = false means the fee is accrued to record Tuleva's cost but kept out of the
-- fund's NAV and out of its ledger.
CREATE TABLE investment_fee_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    fund_code       text        NOT NULL,
    fee_type        text        NOT NULL,
    charged_to_fund boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_to        date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,

    CONSTRAINT investment_fee_policy_pkey PRIMARY KEY (id),
    CONSTRAINT investment_fee_policy_fund_code_fee_type_valid_from_key
        UNIQUE (fund_code, fee_type, valid_from),
    CONSTRAINT investment_fee_policy_valid_range_check
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX investment_fee_policy_fund_code_fee_type_idx
    ON investment_fee_policy (fund_code, fee_type);

-- No default and no fallback: FeeChargedToFundPolicy throws on a missing row, on overlapping rows
-- and on a gap between them. Add rows here when adding a fund, or the NAV run fails for it.
INSERT INTO investment_fee_policy (fund_code, fee_type, charged_to_fund, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'DEPOT', false, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'DEPOT', false, DATE '2026-02-02', 'MIGRATION'),
       ('TUK75', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'MANAGEMENT', true, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'MANAGEMENT', true, DATE '2026-02-02', 'MIGRATION');

-- FIXED: annual_rate is the rate. TIER: the rate comes from investment_depot_fee_tier, resolved
-- at the fee month on the funds' combined aktiva two month ends back (see DepotFeeCalculator).
-- Either way a rate is entered VAT-inclusive; there is no VAT step after this point.
--
-- No CHECK constraint on this column, deliberately: a CHECK added by ALTER is not re-evaluated
-- correctly by H2 once a second Spring context has opened the shared test database, which turns
-- the fee and NAV suites red while PostgreSQL is fine. FeeRepositoriesIntegrationTest asserts the
-- three rules instead -- FIXED or TIER, TIER only for DEPOT, and a TIER row leaves annual_rate 0.
ALTER TABLE investment_fee_rate
    ADD COLUMN rate_source varchar(10) DEFAULT 'FIXED' NOT NULL;

-- Only the NOT NULL goes; the column stays because a previously deployed image both writes and
-- reads daily_amount_net, and FeeAccrualRepository.save dual-writes it for that reason. Drop the
-- column and the dual-write together, once nothing deployed names it.
ALTER TABLE investment_fee_accrual ALTER COLUMN daily_amount_net DROP NOT NULL;

-- The depot fee starts accruing at the real tier rate on 2026-09-18. That date is the depoopank
-- agreement's -- the day the fee becomes payable -- not a deploy convenience, so it does not move.
--
-- Per the Depooleping the fee is charged on aktiva, "Fondi aktivate turuväärtuste summale" -- the
-- gross asset side -- using "tegeliku (aasta ja kuu) päevade arvu meetodit", actual/actual. The
-- management fee's netovara base and fixed 365 come from a different contract.
--
-- IRREVERSIBLE IF DEPLOYED LATE: accruals are forward-only, so any day between 2026-09-18 and the
-- deploy is already written at the old 0 rate and never corrects itself. Recovery is to DELETE the
-- DEPOT rows in investment_fee_accrual from 2026-09-18 and re-run POST /admin/backfill-fees.
UPDATE investment_fee_rate
SET valid_to = DATE '2026-09-17'
WHERE fee_type = 'DEPOT'
  AND rate_source = 'FIXED'
  AND fund_code IN ('TUK75', 'TUK00', 'TUV100', 'TKF100')
  AND valid_from <= DATE '2026-09-17'
  AND (valid_to IS NULL OR valid_to > DATE '2026-09-17');

INSERT INTO investment_fee_rate
    (fund_code, fee_type, annual_rate, rate_source, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TUK00', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TUV100', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TKF100', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION');
