CREATE TABLE investment_instrument_fee_agreement (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY,
    isin                     varchar(12)     NOT NULL,
    published_ocf            numeric(10, 8)  NOT NULL,
    rebate_kind              varchar(20)     NOT NULL,
    rebate_terms             text            NOT NULL DEFAULT '{}',
    invoiced_fee_rate        numeric(10, 8)  NOT NULL DEFAULT 0,
    published_management_fee numeric(10, 8),
    valid_from               date            NOT NULL,
    valid_to                 date,
    source                   text,
    created_at               timestamptz     NOT NULL DEFAULT now(),

    CONSTRAINT pk_instrument_fee_agreement PRIMARY KEY (id),
    CONSTRAINT uq_instrument_fee_agreement_isin_valid_from UNIQUE (isin, valid_from),
    CONSTRAINT fk_instrument_fee_agreement_instrument
        FOREIGN KEY (isin) REFERENCES instrument_reference (isin),
    CONSTRAINT chk_instrument_fee_agreement_published_ocf_is_positive CHECK (published_ocf > 0),
    CONSTRAINT chk_instrument_fee_agreement_invoiced_is_a_charge CHECK (invoiced_fee_rate >= 0),
    CONSTRAINT chk_instrument_fee_agreement_management_fee_is_not_negative
        CHECK (published_management_fee >= 0),
    CONSTRAINT chk_instrument_fee_agreement_rebate_kind
        CHECK (rebate_kind IN ('NONE', 'FIXED', 'FIXED_NET', 'SHARE_OF_PUBLISHED', 'TIERED_VOLUME')),
    CONSTRAINT chk_instrument_fee_agreement_fixed_net_carries_the_whole_cost
        CHECK (rebate_kind <> 'FIXED_NET' OR invoiced_fee_rate = 0),
    CONSTRAINT chk_instrument_fee_agreement_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

INSERT INTO investment_instrument_fee_agreement
    (isin, published_ocf, rebate_kind, rebate_terms, invoiced_fee_rate, valid_from, valid_to, source,
     created_at)
SELECT isin,
       published_ocf,
       CASE WHEN rebate_rate > 0 THEN 'FIXED' ELSE 'NONE' END,
       CASE WHEN rebate_rate > 0
            THEN '{"rate":"' || CAST(rebate_rate AS varchar(20)) || '"}'
            ELSE '{}' END,
       invoiced_fee_rate,
       valid_from,
       valid_to,
       source,
       created_at
FROM investment_instrument_fee;

DROP TABLE investment_instrument_fee;

ALTER TABLE investment_instrument_fee_agreement RENAME TO investment_instrument_fee;

CREATE INDEX idx_instrument_fee_agreement_valid_from ON investment_instrument_fee (valid_from);

CREATE TABLE investment_instrument_fee_rate (
    id                bigint GENERATED BY DEFAULT AS IDENTITY,
    isin              varchar(12)     NOT NULL,
    period_start      date            NOT NULL,
    period_end        date            NOT NULL,
    published_ocf     numeric(10, 8)  NOT NULL,
    rebate_rate       numeric(10, 8)  NOT NULL,
    invoiced_fee_rate numeric(10, 8)  NOT NULL,
    net_ocf           numeric(10, 8)  NOT NULL,
    rate_basis        varchar(20)     NOT NULL,
    fallback_reason   text,
    rebate_kind       varchar(20)     NOT NULL,
    volume_eur        numeric(19, 2),
    volume_nav_date   date,
    eur_usd           numeric(19, 8),
    instrument_fee_id bigint          NOT NULL,
    created_at        timestamptz     NOT NULL DEFAULT now(),

    CONSTRAINT pk_instrument_fee_rate PRIMARY KEY (id),
    CONSTRAINT fk_instrument_fee_rate_agreement
        FOREIGN KEY (instrument_fee_id) REFERENCES investment_instrument_fee (id),
    CONSTRAINT chk_instrument_fee_rate_basis
        CHECK (rate_basis IN ('AGREEMENT', 'PUBLISHED_FALLBACK')),
    CONSTRAINT chk_instrument_fee_rate_a_fallback_says_why
        CHECK ((rate_basis = 'PUBLISHED_FALLBACK') = (fallback_reason IS NOT NULL)),
    CONSTRAINT chk_instrument_fee_rate_rebate_is_a_discount CHECK (rebate_rate >= 0),
    CONSTRAINT chk_instrument_fee_rate_invoiced_is_a_charge CHECK (invoiced_fee_rate >= 0),
    CONSTRAINT chk_instrument_fee_rate_net_adds_up
        CHECK (net_ocf = published_ocf - rebate_rate + invoiced_fee_rate),
    CONSTRAINT chk_instrument_fee_rate_period CHECK (period_end >= period_start)
);

CREATE INDEX idx_instrument_fee_rate_isin_period
    ON investment_instrument_fee_rate (isin, period_start, period_end);
CREATE INDEX idx_instrument_fee_rate_agreement ON investment_instrument_fee_rate (instrument_fee_id);

CREATE TABLE investment_ocf_snapshot_detail (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY,
    snapshot_id            bigint          NOT NULL,
    isin                   varchar(12)     NOT NULL,
    weight                 numeric(19, 12) NOT NULL,
    published_ocf          numeric(10, 8)  NOT NULL,
    net_ocf                numeric(10, 8)  NOT NULL,
    rate_basis             varchar(20)     NOT NULL,
    instrument_fee_rate_id bigint          NOT NULL,

    CONSTRAINT pk_ocf_snapshot_detail PRIMARY KEY (id),
    CONSTRAINT uq_ocf_snapshot_detail_snapshot_isin UNIQUE (snapshot_id, isin),
    CONSTRAINT fk_ocf_snapshot_detail_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES investment_ocf_snapshot (id) ON DELETE CASCADE,
    CONSTRAINT fk_ocf_snapshot_detail_rate
        FOREIGN KEY (instrument_fee_rate_id) REFERENCES investment_instrument_fee_rate (id)
);

CREATE INDEX idx_ocf_snapshot_detail_rate ON investment_ocf_snapshot_detail (instrument_fee_rate_id);
