CREATE TABLE investment_ocf_snapshot (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_code               text            NOT NULL,
    snapshot_month          date            NOT NULL,
    management_fee_rate     numeric(10, 8)  NOT NULL,
    depot_fee_rate          numeric(10, 8)  NOT NULL,
    underlying_fund_cost    numeric(10, 8)  NOT NULL,
    transaction_cost_rate   numeric(10, 8)  NOT NULL,
    total_ocf               numeric(10, 8)  NOT NULL,
    created_at              timestamptz     NOT NULL DEFAULT now(),

    CONSTRAINT investment_ocf_snapshot_fund_month_key
        UNIQUE (fund_code, snapshot_month)
);

CREATE INDEX idx_ocf_snapshot_fund ON investment_ocf_snapshot (fund_code, snapshot_month);
