CREATE TABLE investment_fee_policy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    fund_code       text        NOT NULL,
    fee_type        text        NOT NULL,
    charged_to_fund boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_to        date,
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      text,

    CONSTRAINT investment_fee_policy_pkey PRIMARY KEY (id),
    CONSTRAINT investment_fee_policy_fund_code_fee_type_valid_from_key
        UNIQUE (fund_code, fee_type, valid_from),
    CONSTRAINT investment_fee_policy_valid_range_check
        CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX investment_fee_policy_fund_code_fee_type_idx
    ON investment_fee_policy (fund_code, fee_type);

INSERT INTO investment_fee_policy (fund_code, fee_type, charged_to_fund, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'DEPOT', false, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'DEPOT', false, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'DEPOT', false, DATE '2026-02-02', 'MIGRATION'),
       ('TUK75', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUK00', 'MANAGEMENT', true, DATE '2017-03-28', 'MIGRATION'),
       ('TUV100', 'MANAGEMENT', true, DATE '2019-10-15', 'MIGRATION'),
       ('TKF100', 'MANAGEMENT', true, DATE '2026-02-02', 'MIGRATION');

ALTER TABLE investment_fee_rate
    ADD COLUMN rate_source varchar(10) DEFAULT 'FIXED' NOT NULL;

ALTER TABLE investment_fee_accrual ALTER COLUMN daily_amount_net DROP NOT NULL;

UPDATE investment_fee_rate
SET valid_to = DATE '2026-09-17'
WHERE fee_type = 'DEPOT'
  AND rate_source = 'FIXED'
  AND fund_code IN ('TUK75', 'TUK00', 'TUV100', 'TKF100')
  AND valid_from <= DATE '2026-09-17'
  AND (valid_to IS NULL OR valid_to > DATE '2026-09-17');

INSERT INTO investment_fee_rate
    (fund_code, fee_type, annual_rate, rate_source, valid_from, created_by)
VALUES ('TUK75', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TUK00', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TUV100', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION'),
       ('TKF100', 'DEPOT', 0, 'TIER', DATE '2026-09-18', 'MIGRATION');
