CREATE TABLE investment_cash_buffer_review (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY,
    fund_code                       text            NOT NULL,
    review_month                    date            NOT NULL,
    reviewed_on                     date            NOT NULL,
    window_start_month              date            NOT NULL,
    window_months                   integer         NOT NULL,
    outflow_percentile              numeric(19, 10) NOT NULL,
    outflow_at_percentile           numeric(19, 2)  NOT NULL,
    inflow_percentile               numeric(19, 10) NOT NULL,
    inflow_at_percentile            numeric(19, 2)  NOT NULL,
    inflow_credit                   numeric(19, 10) NOT NULL,
    settlement_horizon_days         integer         NOT NULL,
    horizon_outflow_at_percentile   numeric(19, 2)  NOT NULL,
    accrued_fees                    numeric(19, 2)  NOT NULL,
    recommended_soft                numeric(19, 2)  NOT NULL,
    recommended_hard                numeric(19, 2)  NOT NULL,
    configured_limit_effective_date date            NOT NULL,
    configured_reserve_soft         numeric(19, 2)  NOT NULL,
    configured_reserve_hard         numeric(19, 2),
    drift_threshold                 numeric(19, 10) NOT NULL,
    sustain_runs                    integer         NOT NULL,
    soft_divergence                 numeric(19, 2)  NOT NULL,
    soft_drifted                    boolean         NOT NULL,
    soft_consecutive_drifted_runs   integer         NOT NULL,
    hard_divergence                 numeric(19, 2),
    hard_drifted                    boolean,
    hard_consecutive_drifted_runs   integer,
    unrecognised_payouts            integer         NOT NULL,
    unrecognised_outflow            numeric(19, 2)  NOT NULL,
    created_at                      timestamptz     NOT NULL DEFAULT now(),

    CONSTRAINT investment_cash_buffer_review_pkey PRIMARY KEY (id),
    CONSTRAINT investment_cash_buffer_review_fund_month_key UNIQUE (fund_code, review_month)
);

CREATE TABLE investment_cash_buffer_review_month (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY,
    review_id            bigint          NOT NULL,
    flow_month           date            NOT NULL,
    inflow               numeric(19, 2)  NOT NULL,
    recurring_outflow    numeric(19, 2)  NOT NULL,
    tail_outflow         numeric(19, 2)  NOT NULL,
    cycle_outflow        numeric(19, 2)  NOT NULL,
    unrecognised_outflow numeric(19, 2)  NOT NULL,
    unrecognised_payouts integer         NOT NULL,

    CONSTRAINT investment_cash_buffer_review_month_pkey PRIMARY KEY (id),
    CONSTRAINT investment_cash_buffer_review_month_review_fkey
        FOREIGN KEY (review_id) REFERENCES investment_cash_buffer_review (id),
    CONSTRAINT investment_cash_buffer_review_month_review_month_key UNIQUE (review_id, flow_month)
);

INSERT INTO investment_parameter (effective_date, parameter_name, fund_code, numeric_value)
VALUES
    ('2026-09-28', 'CASH_BUFFER_OUTFLOW_PERCENTILE', NULL, 0.95),
    ('2026-09-28', 'CASH_BUFFER_INFLOW_PERCENTILE', NULL, 0.20),
    ('2026-09-28', 'CASH_BUFFER_INFLOW_CREDIT', NULL, 0),
    ('2026-09-28', 'CASH_BUFFER_SETTLEMENT_HORIZON_DAYS', NULL, 4),
    ('2026-09-28', 'CASH_BUFFER_DRIFT_THRESHOLD', NULL, 50000),
    ('2026-09-28', 'CASH_BUFFER_DRIFT_CONSECUTIVE_RUNS', NULL, 6);
