ALTER TABLE scheduled_email
  RENAME TO email;

ALTER TABLE email
  ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'SCHEDULED';

ALTER TABLE email
  ALTER COLUMN status DROP DEFAULT;

UPDATE email SET type = 'THIRD_PILLAR_SUGGEST_SECOND_PILLAR' WHERE type = 'SUGGEST_SECOND_PILLAR';
UPDATE email SET type = 'THIRD_PILLAR_PAYMENT_REMINDER_MANDATE' WHERE type = 'REMIND_THIRD_PILLAR_PAYMENT';
