package ee.tuleva.onboarding.payment

import spock.lang.Specification
import static ee.tuleva.onboarding.payment.PaymentProviderConfigurationFixture.aPaymentProviderBankConfiguration

class PaymentProviderCallbackServiceSpec extends Specification {
  PaymentProviderCallbackService paymentProviderCallbackService

  Map<String, PaymentProviderBankConfiguration> paymentProviderBankConfigurations
      = [:]
  void setup() {
    paymentProviderBankConfigurations.put(Bank.LHV.getBeanName(), aPaymentProviderBankConfiguration())
    paymentProviderCallbackService = new PaymentProviderCallbackService(paymentProviderBankConfigurations)
  }

  void processToken() {
    given:
    def token = "eyJhbGciOiJIUzI1NiJ9.eyJtZXJjaGFudF9yZXR1cm5fdXJsIjoiaHR0cHM6Ly9vbmJvYXJkaW5nLXNlcnZpY2UudHVsZXZhLmVlL3YxL3BheW1lbnRzL3N1Y2Nlc3MiLCJhbW91bnQiOjEwLCJwYXltZW50X2luZm9ybWF0aW9uX3Vuc3RydWN0dXJlZCI6IjMwMTAxMTE5ODI4IiwiY2hlY2tvdXRfZmlyc3RfbmFtZSI6IkpvcmRhbiIsIm1lcmNoYW50X25vdGlmaWNhdGlvbl91cmwiOiJodHRwczovL29uYm9hcmRpbmctc2VydmljZS50dWxldmEuZWUvdjEvcGF5bWVudHMvbm90aWZpY2F0aW9uIiwicHJlc2VsZWN0ZWRfYXNwc3AiOiJleGFtcGxlQXNwc3AiLCJtZXJjaGFudF9yZWZlcmVuY2UiOiJ7XCJwZXJzb25hbENvZGVcIjogXCIxMjM0NDM0MzRcIiwgXCJ1dWlkXCI6IFwiMjMzMlwifSIsImFjY2Vzc19rZXkiOiJleGFtcGxlQWNjZXNzS2V5IiwicGF5bWVudF9pbmZvcm1hdGlvbl9zdHJ1Y3R1cmVkIjoiOTkzNDMyNDMyIiwiY3VycmVuY3kiOiJFVVIiLCJleHAiOjE2MDYxMjYyMDAsInByZXNlbGVjdGVkX2xvY2FsZSI6ImV0IiwiY2hlY2tvdXRfbGFzdF9uYW1lIjoiVmFsZG1hIn0.O5zhG_x5Fb6a8jFFaLmPi6bCyH1b9wk5P3EOn08r3Tk"
    when:
    paymentProviderCallbackService.processToken(token)
    then:
    true
  }
}
