server:
  port: 9000
  error.whitelabel.enabled: false
  session:
    timeout: 1800

spring:
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/tuleva-onboarding
    username: tuleva-onboarding
    password: tuleva-onboarding
    initialize: true
    continue-on-error: false
    test-on-borrow: true
    test-while-idle: true
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false

security:
  oauth2:
    resource:
      filter-order: 3

xroad:
  instance: ee-dev
  kprEndpoint: https://zoot.ml.ee/cgi-bin/TreasuryXrdWS/services/TreasuryXrdWS
  memberClass: COM
  memberCode: 14041764
  subsystemCode: tuleva
  requestTimeout: 5000
  connectionTimeout: 3000

ssl:
  trustAllHTTPSHosts: true

digidoc:
  service:
    url: https://tsp.demo.sk.ee/

mobile-id:
  service:
    name: "Testimine"

truststore:
  path: "test_keys/truststore.jks"

mandate:
  email:
    from: "avaldused@tuleva.ee"
    to: "avaldused.test@tuleva.ee"
    bcc: "avaldused@tuleva.ee"

mhub:
  host: mhub.e-register.ee
  port: 2414
  queueManager: MHUB_QMGR
  channel: TULEVA
  peerName: "CN=mhub.e-register.ee, OU=IT, O=Eesti Vaartpaberikeskus AS, C=EE, L=Tallinn, ST=Harjumaa"
  inboundQueue: MHUB.PRIVATE.TULEVA.OUT
  outboundQueue: MHUB.PRIVATE.IN
  keyStore: ${MHUB_KEYSTORE}
  keyStorePassword: ${MHUB_KEYSTORE_PASSWORD}
  trustStore: ${MHUB_KEYSTORE}
  trustStorePassword: ${MHUB_KEYSTORE_PASSWORD}

socksProxyUrl: ${SOCKS_PROXY_URL:#{null}}

proxy:
  url: ${QUOTAGUARDSTATIC_URL}
  nonProxyHosts: "mandrillapp.com|sk.ee|localhost"
